apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "appmesh-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "appmesh-controller.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleARN }}
