version: "3"
services:
    resources-api:
        image: erankitcs/bookstoreapp_resources-api
        ports: 
            - 5000:5000
        environment:
            DYNAMODB_TABLE: development-resources
            AWS_DEFAULT_REGION: us-west-2
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_XRAY_SDK_ENABLED: "false"
    inventory-api:
        image: erankitcs/bookstoreapp_inventory-api
        ports: 
            - "5001:5001"
        links:
            - resources-api
        environment: 
            DYNAMODB_TABLE: development-inventory
            RESOURCE_API_ENDPOINT: http://resources-api:5000
            AWS_DEFAULT_REGION: us-west-2
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    clients-api:
        image: erankitcs/bookstoreapp_clients-api
        ports: 
            - "5003:5003"
        environment: 
            AWS_DEFAULT_REGION: us-west-2
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    renting-api:
        image: erankitcs/bookstoreapp_renting-api
        ports:
          - "5004:3000"
        environment:
          AWS_DEFAULT_REGION: us-west-2
          AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
          AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
          DYNAMODB_TABLE: development-renting
          INVENTORY_API_ENDPOINT: http://inventory-api:5001
          CLIENTS_API_ENDPOINT: http://clients-api:5003
          RESOURCES_API_ENDPOINT: http://resources-api:5000
    proxy:
        image: nginx:stable-alpine
        ports: 
            - 80:80
        depends_on: 
            - resources-api
            - inventory-api
            - front-end
        volumes: 
            - ./default.conf:/etc/nginx/conf.d/default.conf
    front-end:
        image: erankitcs/bookstoreapp_front-end
        ports: 
            - "5002:80"
        volumes: 
            - ./front-end-config.json:/usr/share/nginx/html/assets/json/config.json