apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookstore-inventory-api.name" . }}-service
  labels:
    {{- include "bookstore-inventory-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bookstore-inventory-api.selectorLabels" . | nindent 4 }}
