{{- if .Values.mesh.enabled -}}
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: {{ template "bookstore-front-end.name" . }}-proxy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "bookstore-front-end.name" . }}-proxy
      release: {{ .Release.Name }}
  listeners:
    - portMapping:
        port: {{ .Values.service.port }}
        protocol: http
  serviceDiscovery:
    dns:
      hostname: {{ include "bookstore-front-end.name" . }}-proxy-service.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}