apiVersion: v1
kind: Service
metadata:
  name: {{ template "bookstore-front-end.name" . }}-proxy-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "bookstore-front-end.name" . }}-proxy
    chart: {{ template "bookstore-front-end.chart" . }}-proxy
    release: {{ .Release.Name }}-proxy
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "bookstore-front-end.name" . }}-proxy
    release: {{ .Release.Name }}
